import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css"
// import CursorCircle from "./cursorFollow";
import HideShow from "./funcs/hideShow"
import TextSlider from "./funcs/textSlider";
import Link from "next/link";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <div className="circle" id="cursorCircle"></div> */}
          {/* <CursorCircle /> */}
          <HideShow />

          <TextSlider />
          <div className="contentContainer">
            <img src="/icons/star-icon.svg" alt="icon" className="icon" />
              <div className="homeNavbar">
                  {/* <div className="navbarElement" id="allButton">All</div> */}
                  <Link href="/" className="navbarElement"><div id="aboutButton">About Me</div></Link>
                  <Link href="/projects" className="navbarElement"><div id="projectsButton">Projects</div></Link>
                  <Link href="/work" className="navbarElement"><div id="workButton">Work</div></Link>
                  <Link href="/hobby" className="navbarElement"><div id="hobbyButton">Hobby</div></Link>
                </div>
              {children}
            </div>
      </body>
    </html>
  );
}
